### ISSUE TITLE
Getting TypeError: Cannot read property 'hasOwnProperty' of undefined when using with react-three-fiber

### ISSUE THREAD

**Issue by v1rtl** [developit/nextjs-preact-demo#12]
I get this error in development mode when I start the server:

```
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at $$$reconciler (/home/v1rtl/Coding/v1rtl-2/node_modules/.pnpm/registry.npmjs.org/react-reconciler/0.24.0_react@1.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:143:27)
    at Object.<anonymous> (/home/v1rtl/Coding/v1rtl-2/node_modules/.pnpm/registry.npmjs.org/react-three-fiber/4.0.20_64fe8dc265668c65cc86300ef354a689/node_modules/react-three-fiber/web.cjs.js:423:16)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.react-three-fiber (/home/v1rtl/Coding/v1rtl-2/.next/server/static/development/pages/index.js:1990:18)
    at __webpack_require__ (/home/v1rtl/Coding/v1rtl-2/.next/server/static/development/pages/index.js:23:31)
    at Module../components/WebGL/Wave.tsx (/home/v1rtl/Coding/v1rtl-2/.next/server/static/development/pages/index.js:1211:75)
    at __webpack_require__ (/home/v1rtl/Coding/v1rtl-2/.next/server/static/development/pages/index.js:23:31)
    at Module../components/ProjectView.tsx (/home/v1rtl/Coding/v1rtl-2/.next/server/static/development/pages/index.js:639:69)
    at __webpack_require__ (/home/v1rtl/Coding/v1rtl-2/.next/server/static/development/pages/index.js:23:31)
    at Module../components/Sites.tsx (/home/v1rtl/Coding/v1rtl-2/.next/server/static/development/pages/index.js:922:70)
    at __webpack_require__ (/home/v1rtl/Coding/v1rtl-2/.next/server/static/development/pages/index.js:23:31)
```

I use `react-three-fiber` which is a React reconciler for THREE, so maybe it's the source of the problem.

Here's the info that can be useful:

* `pnpm`: 4.14.0
* `node` 13.3.0
* `next`: 9.3.5
* `preact`: 10.4.1
* `react-three-fiber`: 4.0.20

I can create a reproduction codesandbox, if required

**Comment by developit** [comment]
Hiya - yeah this definitely won't work with `react-three-fiber`, since Preact can't support custom renderers. I'm going to close this as wontfix since there's no plans in this space.

**Comment by v1rtl** [comment]
@developit ok, sounds right!

I keep forgetting that preact uses browser APIs instead of abstrations lol
